global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "image-classifier"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 5s
    scrape_timeout: 3s
